# Generated by Django 3.2.12 on 2022-03-07 20:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Base_legale',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('contenu', models.CharField(blank=True, max_length=255)),
                ('link', models.CharField(blank=True, max_length=255)),
                ('page_number', models.IntegerField(blank=True, null=True)),
                ('added_on', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Categorie_acte',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
                ('added_on', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Source_des_donnees',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('link', models.CharField(blank=True, max_length=255)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('added_on', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Type_de_centre',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('added_on', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Acte',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('page_number', models.IntegerField(blank=True, null=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
                ('finalite', models.CharField(max_length=255)),
                ('dossier', models.CharField(max_length=255)),
                ('cout', models.CharField(max_length=255)),
                ('cout_minimum', models.CharField(blank=True, max_length=255, null=True)),
                ('cout_maximum', models.CharField(blank=True, max_length=255, null=True)),
                ('precision_cout', models.CharField(blank=True, max_length=255, null=True)),
                ('validite', models.CharField(blank=True, max_length=255, null=True)),
                ('delai_de_delivrance', models.CharField(blank=True, max_length=255, null=True)),
                ('lieu_de_retrait', models.CharField(blank=True, max_length=255, null=True)),
                ('quittance_recu_timbre', models.CharField(max_length=255)),
                ('added_on', models.DateTimeField(auto_now_add=True)),
                ('base_legale_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AppGestionDesActes.base_legale')),
                ('categorie_acte_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AppGestionDesActes.categorie_acte')),
                ('source_des_donnees_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AppGestionDesActes.source_des_donnees')),
                ('types_de_centre', models.ManyToManyField(to='AppGestionDesActes.Type_de_centre')),
            ],
        ),
    ]
