# Generated by Django 3.2.12 on 2022-03-10 12:46

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('AppGestionDesActes', '0002_preoccupation'),
    ]

    operations = [
        migrations.CreateModel(
            name='Type_preoccupation',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('added_on', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='preoccupation',
            name='added_on',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='preoccupation',
            name='types_preoccupation',
        ),
        migrations.AddField(
            model_name='preoccupation',
            name='types_preoccupation',
            field=models.ManyToManyField(blank=True, to='AppGestionDesActes.Type_preoccupation'),
        ),
    ]
