# Generated by Django 3.2.12 on 2022-03-18 21:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AppGestionDesActes', '0004_domaine'),
    ]

    operations = [
        migrations.AddField(
            model_name='acte',
            name='domaine_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='AppGestionDesActes.domaine'),
        ),
    ]
