# Generated by Django 3.2.12 on 2022-03-19 13:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppGestionDesActes', '0005_acte_domaine_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='domaine',
            old_name='Description',
            new_name='description',
        ),
    ]
