# Generated by Django 3.2.12 on 2022-05-11 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppGestionDesActes', '0006_rename_description_domaine_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='base_legale',
            name='contenu',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='base_legale',
            name='name',
            field=models.CharField(max_length=500),
        ),
    ]
