# Generated by Django 3.2.12 on 2022-05-11 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppGestionDesActes', '0009_auto_20220511_1225'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acte',
            name='precision_cout',
            field=models.TextField(blank=True, null=True),
        ),
    ]
